package com.hanlyjiang.learnandroid.document.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hanlyjiang.learnandroid.document.db.CaseFile;

import com.hanlyjiang.learnandroid.document.db.CaseFileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig caseFileDaoConfig;

    private final CaseFileDao caseFileDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        caseFileDaoConfig = daoConfigMap.get(CaseFileDao.class).clone();
        caseFileDaoConfig.initIdentityScope(type);

        caseFileDao = new CaseFileDao(caseFileDaoConfig, this);

        registerDao(CaseFile.class, caseFileDao);
    }
    
    public void clear() {
        caseFileDaoConfig.getIdentityScope().clear();
    }

    public CaseFileDao getCaseFileDao() {
        return caseFileDao;
    }

}
